### ISSUE TITLE
IS THIS REPO DEAD?

### ISSUE THREAD

**Issue by limonte** [feross/thanks#122]
You're not responding to any of PRs a couple of months already.

As I mentioned in #119 many links are 404 and it will be even worse with time.

If you don't have time to maintain this repo, consider [archiving it](https://help.github.com/articles/archiving-a-github-repository/)

> When you archive a repository, you are letting people know that a project is no longer actively maintained.

**Comment by zeke** [comment]
I can't comment on behalf of @feross, nor am I maintainer of this project, but I love the idea and would love to see it succeed. Perhaps life in a new org with more maintainers could help breathe new life into this repo?

**Comment by limonte** [comment]
Yup, it's dead.

**Comment by feross** [comment]
Project is not dead, was just hibernating because I started a masters degree. If you don't like the way I run this project, feel free to start your own.

**Comment by feross** [comment]
Also, I'm always happy to add maintainers to a repo if I know the maintainer personally (i.e. @zeke) or after a track record of useful PRs to my projects. Just added you to this repo, @zeke.

**Comment by limonte** [comment]
> Project is not dead, was just hibernating because I started a masters degree. If you don't like the way I run this project, feel free to start your own.

The better question is: do you like the way this project runs? Publishing a lot of projects and abandoning them for a couple of months look like the ancient way of humanity when humans were making as many children as possible with the hope that some of them will somehow survive.

In the current western world we're maintaining our children and our projects in the beginning of their lives on the regular basis.

**Comment by feross** [comment]
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT

Also, you are now banned.
