### ISSUE TITLE
Helping `thanks`

### ISSUE THREAD

**Issue by znarf** [feross/thanks#125]
I see Pull Requests to `thanks` are not merged for a while. Can I help?

As the creator and maintainer of [BackYourStack](https://github.com/opencollective/backyourstack), I have some experience in the field and I can work on some data exchanges between the projects. I already issued a PR but had no feedback: https://github.com/feross/thanks/pull/115

I would like to propose my help maintaining the project: update data, merge PRs, review dead links, issue new versions.

**Comment by feross** [comment]
Hey @znarf, happy to see that you're interested in collaborating. I've merged all outstanding PRs except for the one you sent which needs to be updated to fix conflicts. Happy to add you to this repo if you continue to show interest in helping out. Cheers.
