### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [feross/thanks#137]
Hi! @feross I have reviewed and appreciate your repo. I wanted to design a logo for this repository which is popular enough. I designed a powerful idea in a minimalist way. I hope you like it. I'd be happy to send a pr if you want to use it. What do you think? I will wait for feedback. Have a nice day!

![THANKS](https://user-images.githubusercontent.com/36298335/56585685-03f8d280-65e7-11e9-8ca3-80d4f3067423.jpg)

Readme view;

![thankss](https://user-images.githubusercontent.com/36298335/56585708-0b1fe080-65e7-11e9-9586-3fd23275955d.png)

**Comment by feross** [comment]
Very nice concept! Please send a pull request to add this to the project!

**Comment by feross** [comment]
@reallinfo Hey, friendly ping on this! Do you still want to contribute this logo to the project?

**Comment by reallinfo** [comment]
Hey, sorry for late message. I will a pull request. I am glad to your like it :)

**Comment by reallinfo** [comment]
https://github.com/feross/thanks/pull/147

**Comment by feross** [comment]
Thanks :)
