### ISSUE TITLE
Projects vs. individuals

### ISSUE THREAD

**Issue by MikeMcQuaid** [feross/thanks#16]
Hey! Firstly, this is a great idea, thanks for doing it!

I was looking at [`index.js`](https://github.com/feross/thanks/blob/master/index.js) and it all seems to be individuals listed there. Is this intentional or just a coincidence?

I'm wondering if it's worth adding projects here that have a shared Patreon for the project itself. 

Thanks again!

**Comment by feross** [comment]
Hey @MikeMcQuaid! There's a section at the bottom of the file for donate links that belong to projects! See here: https://github.com/feross/thanks/blob/master/index.js#L34-L58

**Comment by MikeMcQuaid** [comment]
@feross Gotcha, sorry for the confusion. Final question: are you planning on keeping this as an `npm`-only thing or extending it to other things (e.g. I'm thinking Homebrew). Thanks again!

**Comment by feross** [comment]
@MikeMcQuaid Going to keep this npm-only for now, I think. I don't know too much about other ecosystems and there have already been a few good projects started for other ecosystems:

- Python https://twitter.com/phildini/status/962412326266785792
- Ruby https://twitter.com/DPritchett/status/962495535847526401
- Go https://github.com/Southclaws/thanks

This seems like the way forward.

I'm not completely against evolving this `thanks` tool into something for all ecosystems. I would just need a lot of help to make that happen, and there would need to be a good argument made for why that's better than a tool-per-ecosystem. Thoughts?

**Comment by MikeMcQuaid** [comment]
> I would just need a lot of help to make that happen, and there would need to be a good argument made for why that's better than a tool-per-ecosystem.

I can't speak to the "needing a lot of help" but from my perspective: this ends up helping the language ecosystem but not system libraries/tools/package managers that the language ecosystem relies on to function. That's not to say you should or shouldn't do anything with this project (it's yours, after all) but just the reason why I'm interest in that.
