### ISSUE TITLE
[REQUEST] Upvote on Product Hunt

### ISSUE THREAD

**Issue by feross** [feross/thanks#19]
Just posted this to @ProductHunt to get it in front of makers who use OSS in their products. ✨

Check it out and consider leaving an upvote: https://www.producthunt.com/posts/thanks ❤️

**Comment by sushruth** [comment]
What terminal do you use! its amazing.

**Comment by feross** [comment]
@sushruth Thanks! I use Zsh with a pre-made configuration called Prezto (https://github.com/sorin-ionescu/prezto) It's really great!

**Comment by feross** [comment]
Thanks for all your votes. Thanks was the second place product of the day! ✨

https://www.producthunt.com/posts/thanks
