### ISSUE TITLE
fails when encountering a package not hosted on npm (e.g., a private github repo)

### ISSUE THREAD

**Issue by 21echoes** [feross/thanks#31]
```
𝄢 npx thanks
💜  Fetching package maintainers from npm...(node:50314) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: 404 Not Found: latest
```

We have some dependencies like `"nion": "github:patreon/nion#c976b369d75892ef39b3f9eb48fed1c6b6a50d0f",` in our codebase, and it tries to look them up on npm using the package name, even if they are not hosted on npm.

This could be fixed by either: detecting that it's a github package OR by handling npm 404s without crashing out.

awesome idea, thanks @feross !

**Comment by feross** [comment]
Released as 1.4.0
