### ISSUE TITLE
Migrate the functionality to NPM

### ISSUE THREAD

**Issue by jonathan-fielding** [feross/thanks#76]
Hey,

I was thinking with all the discussion around how we can move the donation info to the package.json in #2 I was thinking the next logical step would be to move this behaviour from its own npm package into core npm.

Thoughts?

Jonathan

**Comment by feross** [comment]
There was a PR to npm to mention `npx thanks` at install time, here: https://github.com/npm/npm/pull/19817

I think at the moment, the npm team is watching and waiting. They're not interested in integrating this type of functionality just yet.
